src/main/java/edu/avans/hartigehap/domain/Bill.java
package edu.avans.hartigehap.domain;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.Iterator;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * 
 * @author Erco
 */
@Entity
//optional
@Table(name = "BILLS")
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "@id") 
@Getter @Setter
@ToString(callSuper=true, includeFieldNames=true, of= {"billStatus", "currentOrder", "orders"})
public class Bill extends DomainObject {
	private static final long serialVersionUID = 1L;
	
	public enum BillStatus {
		CREATED, SUBMITTED, PAID
	}
	
	// represented in database as integer
	@Enumerated(EnumType.ORDINAL)
	private BillStatus billStatus;
	
	@Temporal(TemporalType.TIMESTAMP)
	private Date submittedTime;
	
	@Temporal(TemporalType.TIMESTAMP)
	private Date paidTime;

	// unidirectional one-to-one relationship
	@OneToOne(cascade = javax.persistence.CascadeType.ALL)
	private Order currentOrder;
	
	@OneToMany(cascade = javax.persistence.CascadeType.ALL, mappedBy = "bill")
	private Collection<Order> orders = new ArrayList<Order>();
	
	// bidirectional one-to-many relationship
	@ManyToOne()
	private DiningTable diningTable;

	// bidirectional one-to-many relationship
	@ManyToOne(cascade = javax.persistence.CascadeType.ALL)
	private Customer customer;
	
	public Bill() {
		billStatus = BillStatus.CREATED;
		currentOrder = new Order();
		currentOrder.setBill(this);
		orders.add(currentOrder);
	}


	/* business logic */

	@Transient
	public Collection<Order> getSubmittedOrders() {
		Collection<Order> submittedOrders = new ArrayList<Order>();
		Iterator<Order> orderIterator = orders.iterator();
		while (orderIterator.hasNext()) {
			Order tmp = orderIterator.next();
			if (tmp.isSubmittedOrSuccessiveState()) {
				submittedOrders.add(tmp);
			}
		}
		return submittedOrders;
	}

	/**
	 * price of *all* orders, so submitted orders and current (not
	 * yet submitted) order
	 * @return
	 */
	@Transient
	public int getPriceAllOrders() {
		int price = 0;
		Iterator<Order> orderIterator = orders.iterator();
		while (orderIterator.hasNext()) {
			price += orderIterator.next().getPrice();
		}
		return price;
	}

	/**
	 * price of the *submitted or successive state* orders only
	 * @return
	 */
	@Transient
	public int getPriceSubmittedOrSuccessiveStateOrders() {
		int price = 0;
		Iterator<Order> orderIterator = orders.iterator();
		while (orderIterator.hasNext()) {
			Order tmp = orderIterator.next();
			if (tmp.isSubmittedOrSuccessiveState()) {
				price += tmp.getPrice();
			}
		}
		return price;
	}

	public void submitOrder() throws StateException {
		currentOrder.submit();
		currentOrder = new Order();
		currentOrder.setBill(this);
		orders.add(currentOrder);
	}

	/*
	 * as the table gets a new bill, there is no risk that a customer keeps
	 * ordering on the submitted or paid bill
	 */
	public void submit() throws StateException, EmptyBillException {
		boolean allEmpty = true;
		Iterator<Order> orderIterator = orders.iterator();
		while (orderIterator.hasNext()) {
			Order order = orderIterator.next();
			if (!order.isEmpty()) {
				allEmpty = false;
				break;
			}
		}
		if (allEmpty) {
			throw new EmptyBillException("not allowed to submit an empty bill");
		}

		if (!currentOrder.isEmpty() && currentOrder.getOrderStatus() == Order.OrderStatus.CREATED) {
			// the currentOrder is not empty, but not yet submitted
			throw new StateException("not allowed to submit an with currentOrder in created state");
		}

		// this can only happen by directly invoking HTTP requests, so not via
		// GUI
		// TODO better to use another exception, because now GUI show wrong
		// error message
		if (billStatus != BillStatus.CREATED) {
			throw new StateException(
			        "not allowed to submit an already submitted bill");
		}

		submittedTime = new Date();
		billStatus = BillStatus.SUBMITTED;
	}

	@Transient
	public boolean isSubmitted() {
		return billStatus == BillStatus.SUBMITTED;
	}

	public void paid() throws StateException {

		// this can only happen by directly invoking HTTP requests, so not via
		// GUI
		if (billStatus != BillStatus.SUBMITTED) {
			throw new StateException(
			        "not allowed to pay an bill that is not in the submitted state");
		}

		paidTime = new Date();
		billStatus = BillStatus.PAID;
	}

}

src/main/java/edu/avans/hartigehap/domain/DiningTable.java
package edu.avans.hartigehap.domain;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * 
 * @author Erco
 */
@Entity
@Table(name = "DININGTABLES")
// optional
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "@id")
@Getter @Setter
@ToString(callSuper=true, includeFieldNames=true, of= {"bills", "currentBill"})
public class DiningTable extends DomainObject {
	private static final long serialVersionUID = 1L;

	private int tableNr;
	
	// example of an *unidirectional* one-to-one relationship, mapped on
	// database by diningTable side
	@OneToOne(cascade = javax.persistence.CascadeType.ALL)
	private Bill currentBill;

	@OneToMany(cascade = javax.persistence.CascadeType.ALL, mappedBy = "diningTable")
	private Collection<Bill> bills = new ArrayList<Bill>();

	@ManyToOne()
	private Restaurant restaurant;

	public DiningTable() {
		// when the system resets, the c'tor is executed and a new Bill object
		// is created (which in its turn creates a new order object. However, 
		// when the dining table becomes managed, the currentBill as was 
		// stored in the database is retrieved, and the new Bill and new Order
		// object, which were not managed yet are discarded.
		currentBill = new Bill();
		currentBill.setDiningTable(this);
		bills.add(currentBill);
	}

	public DiningTable(int tableNr) {
		this.tableNr = tableNr;
		// when the system resets, the c'tor is executed and a new Bill object
		// is created (which in its turn creates a new order object. However, 
		// when the dining table becomes managed, the currentBill as was 
		// stored in the database is retrieved, and the new Bill and new Order
		// object, which were not managed yet are discarded.
		currentBill = new Bill();
		currentBill.setDiningTable(this);
		bills.add(currentBill);
	}

	/* business logic */

	public void warmup() {
		Iterator<OrderItem> orderItemIterator = currentBill.getCurrentOrder()
				.getOrderItems().iterator();
		while (orderItemIterator.hasNext()) {
			orderItemIterator.next().getId();
			// note: menu items have been warmed up via the restaurant->menu
			// relation; therefore it
			// is not needed to warm these objects via this relation
		}
	}

	public void submitBill() throws StateException, EmptyBillException {
		currentBill.submit();
		currentBill = new Bill();
		currentBill.setDiningTable(this);
		bills.add(currentBill);
	}

}

src/main/java/edu/avans/hartigehap/web/controller/CustomerController.java
package edu.avans.hartigehap.web.controller;

import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.mvc.support.*;
import org.springframework.validation.*;
import java.io.IOException;
import java.io.InputStream;
import org.apache.commons.io.IOUtils;
import edu.avans.hartigehap.web.form.*;
import javax.servlet.http.Part;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.MessageSource;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import com.google.common.collect.Lists;
import edu.avans.hartigehap.web.util.*;

import java.util.*;

import edu.avans.hartigehap.domain.*;
import edu.avans.hartigehap.service.*;
import javax.servlet.http.*;

@Controller
@PreAuthorize("hasRole('ROLE_EMPLOYEE')")
public class CustomerController {
	final Logger logger = LoggerFactory.getLogger(CustomerController.class);

	@Autowired
	private MessageSource messageSource;
	@Autowired
	private CustomerService customerService;
	@Autowired
	private RestaurantService restaurantService;
	
	@RequestMapping(value = "/restaurants/{restaurantName}/customers", method = RequestMethod.GET)
	public String listCustomers(@PathVariable("restaurantName") String restaurantName, Model uiModel) {
		
		Restaurant restaurant = warmupRestaurant(restaurantName, uiModel);
		
		logger.info("Listing customers");
		List<Customer> customers = customerService.findCustomersForRestaurant(restaurant);
		uiModel.addAttribute("customers", customers);
		logger.info("No. of customers: " + customers.size());
		
		return "hartigehap/listcustomers";
	}
	
	@RequestMapping(value = "/restaurants/{restaurantName}/customers/{id}", method = RequestMethod.GET)
	public String showCustomer(@PathVariable("restaurantName") String restaurantName, @PathVariable("id") Long id, Model uiModel) {

		warmupRestaurant(restaurantName, uiModel);
		
		logger.info("Show customer: " + id);
		
		Customer customer = customerService.findById(id);
		uiModel.addAttribute("customer", customer);
		return "hartigehap/showcustomer";
	}

	@RequestMapping(value = "/restaurants/{restaurantName}/customers/{id}", params = "form", method = RequestMethod.GET)
	public String updateCustomerForm(@PathVariable("restaurantName") String restaurantName, @PathVariable("id") Long id, Model uiModel) {

		warmupRestaurant(restaurantName, uiModel);
		
		logger.info("Customer update form for customer: " + id);
		
		Customer customer = customerService.findById(id);
		uiModel.addAttribute("customer", customer);
		logger.info("updatingCustomerForm(" + customer.getFirstName() + ", " + customer.getLastName() + ")");
		return "hartigehap/editcustomer";
	}

	@RequestMapping(value = "/restaurants/{restaurantName}/customers/{id}", params = "form", method = RequestMethod.PUT)
	public String updateCustomer(
			// the path variable is not used; data binding retrieves its info from
			// query string parameters and form fields, so customer includes id as well
			@PathVariable("restaurantName") String restaurantName,
			@PathVariable("id") Long id, 
			@Valid Customer customer, 
			BindingResult bindingResult,
			Model uiModel, 
			HttpServletRequest httpServletRequest,
			RedirectAttributes redirectAttributes, 
			Locale locale,
			@RequestParam(required=false) Part file) {
		
		if(bindingResult.hasErrors()) {
			uiModel.addAttribute(
					"message",
					new Message("error", messageSource.getMessage(
							"customer_save_fail", new Object[] {}, locale)));
			uiModel.addAttribute("customer", customer);
			return "hartigehap/editcustomer";
		}
		uiModel.asMap().clear();
		redirectAttributes.addFlashAttribute(
				"message",
				new Message("success", messageSource.getMessage(
						"customer_save_success", new Object[] {}, locale)));

		// Process upload file
        if(file != null) {
			logger.info("File name: " + file.getName());
			logger.info("File size: " + file.getSize());
			logger.info("File content type: " + file.getContentType());
			byte[] fileContent = null;
			try {
				InputStream inputStream = file.getInputStream();
				if(inputStream == null) {
					logger.info("File inputstream is null");
				}
				fileContent = IOUtils.toByteArray(inputStream);
				customer.setPhoto(fileContent);
			} catch (IOException ex) {
				logger.error("Error saving uploaded file", ex);
			}
			customer.setPhoto(fileContent);
		}

        Customer existingCustomer = customerService.findById(customer.getId());
        assert existingCustomer != null : "customer should exist";
        
        // update user-editable fields
        existingCustomer.updateEditableFields(customer);

		customerService.save(existingCustomer);
		return "redirect:/restaurants/" + restaurantName + "/customers/"
				+ UrlUtil.encodeUrlPathSegment(customer.getId().toString(),
						httpServletRequest);
	}

	@RequestMapping(value = "/restaurants/{restaurantName}/customers", params = "form", method = RequestMethod.GET)
	public String createCustomerForm(@PathVariable("restaurantName") String restaurantName, Model uiModel) {

		warmupRestaurant(restaurantName, uiModel);
		
		logger.info("Create customer form");
		
		Customer customer = new Customer();
		uiModel.addAttribute("customer", customer);
		return "hartigehap/editcustomer";
	}
	

	@RequestMapping(value = "/restaurants/{restaurantName}/customers", params = "form", method = RequestMethod.POST)
	public String createCustomer(@PathVariable("restaurantName") String restaurantName, @Valid Customer customer, BindingResult bindingResult,
		Model uiModel, HttpServletRequest httpServletRequest,
		RedirectAttributes redirectAttributes, Locale locale,
		@RequestParam(value = "file", required = false) Part file) {

		logger.info("Creating customer: " + customer.getFirstName() + " " + customer.getLastName());	
		logger.info("Binding Result target: " + (Customer) bindingResult.getTarget()); 
		logger.info("Binding Result: " + bindingResult);
		
		if(bindingResult.hasErrors()) {
			uiModel.addAttribute(
					"message",
					new Message("error", messageSource.getMessage(
							"customer_save_fail", new Object[] {}, locale)));
			uiModel.addAttribute("customer", customer);
			return "hartigehap/editcustomer";
		}
		uiModel.asMap().clear();
		redirectAttributes.addFlashAttribute(
				"message",
				new Message("success", messageSource.getMessage(
						"customer_save_success", new Object[] {}, locale)));
		
		// Process upload file
		if(file != null) {
			logger.info("File name: " + file.getName());
			logger.info("File size: " + file.getSize());
			logger.info("File content type: " + file.getContentType());
			byte[] fileContent = null;
			try {
				InputStream inputStream = file.getInputStream();
				if(inputStream == null) {
					logger.info("File inputstream is null");
				}
				fileContent = IOUtils.toByteArray(inputStream);
				customer.setPhoto(fileContent);
			} catch (IOException ex) {
				logger.error("Error saving uploaded file", ex);
			}
			customer.setPhoto(fileContent);
		}

		// relate customer to current restaurant
		Restaurant restaurant = warmupRestaurant(restaurantName, uiModel);
		customer.setRestaurants(Arrays.asList(new Restaurant[]{restaurant}));
		
		// to get the auto generated id
		Customer storedCustomer = customerService.save(customer);
		
		return "redirect:/restaurants/" + restaurantName + "/customers/"
				+ UrlUtil.encodeUrlPathSegment(storedCustomer.getId().toString(),
						httpServletRequest);
	}

	@RequestMapping(value = "/restaurants/{restaurantName}/customers/{id}/photo", method = RequestMethod.GET)
	@ResponseBody
	public byte[] downloadPhoto(@PathVariable("id") Long id) {
		Customer customer = customerService.findById(id);
		if(customer.getPhoto() != null) {
			logger.info("Downloading photo for id: {} with size: {}",
					customer.getId(), customer.getPhoto().length);
		}
		return customer.getPhoto();
	}

	// to be truly RESTful use DELETE instead of GET
	@RequestMapping(value = "/restaurants/{restaurantName}/customers/{id}", params = "delete", method = RequestMethod.GET)
	public String delete(@PathVariable("restaurantName") String restaurantName, @PathVariable("id") Long id) {

		logger.info("Deleting customer: " + id);
		customerService.delete(id);
		return "redirect:/restaurants/" + restaurantName + "/customers/";
	}


	@RequestMapping(value = "/restaurants/{restaurantName}/customers/listgrid", method = RequestMethod.GET, produces = "application/json")
	@ResponseBody
	public CustomerGrid listGrid(
			@PathVariable("restaurantName") String restaurantName,
			@RequestParam(value = "page", required = false) Integer page,
			@RequestParam(value = "rows", required = false) Integer rows,
			@RequestParam(value = "sidx", required = false) String sortBy,
			@RequestParam(value = "sord", required = false) String order) {
		logger.info("Listing customers for grid with page: {}, rows: {}", page,
				rows);
		logger.info("Listing customers for grid with sort: {}, order: {}",
				sortBy, order);
		// Process order by
		Sort sort = null;
		String orderBy = sortBy;
		if(orderBy != null && "birthDateString".equals(orderBy)) {
			orderBy = "birthDate";
		}
		if(orderBy != null && order != null) {
			if ("desc".equals(order)) {
				sort = new Sort(Sort.Direction.DESC, orderBy);
			} else {
				sort = new Sort(Sort.Direction.ASC, orderBy);
			}
		}

		// Constructs page request for current page
		// Note: page number for Spring Data JPA starts with 0, while jqGrid
		// starts with 1
		PageRequest pageRequest = null;
		if(sort != null) {
			pageRequest = new PageRequest(page - 1, rows, sort);
		} else {
			pageRequest = new PageRequest(page - 1, rows);
		}

		// no need to warmup, as is ajax

src/main/webapp/WEB-INF/views/hartigehap/diningtable.jspx
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<div id="body" xmlns:jsp="http://java.sun.com/JSP/Page"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:joda="http://www.joda.org/joda/time/tags"
	xmlns:spring="http://www.springframework.org/tags"
	xmlns:form="http://www.springframework.org/tags/form"
	xmlns:sec="http://www.springframework.org/security/tags" version="2.0">
	<jsp:directive.page contentType="text/html;charset=UTF-8" />
	<jsp:output omit-xml-declaration="yes" />

	<spring:message code="label_dining_menu" var="labelDiningMenu" />
	<spring:message code="label_restaurant" var="labelRestaurant" />
	<spring:message code="label_current_order" var="labelCurrentOrder" />
	<spring:message code="label_submit_order_button"
		var="labelSubmitOrderButton" />
	<spring:message code="label_current_bill" var="labelCurrentBill" />
	<spring:message code="label_submit_bill_button"
		var="labelSubmitBillButton" />
	<spring:message code="label_price_current_order"
		var="labelPriceCurrentOrder" />
	<spring:message code="label_total_price_prev_orders"
		var="labelTotalPricePrevOrders" />
	<spring:message code="label_menu_item" var="labelMenuItem" />
	<spring:message code="label_food_category" var="labelFoodCategory" />
	<spring:message code="label_price" var="labelPrice" />
	<spring:message code="label_add_button" var="labelAddButton" />
	<spring:message code="label_remove_button" var="labelRemoveButton" />
	<spring:message code="label_currency" var="labelCurrency" />
	<spring:url var="showRestaurant" value="/restaurants/${restaurant.id}" />

	<h1>
		${labelDiningMenu} ${diningTable.tableNr} (${labelRestaurant} <a
			href="${showRestaurant}">${restaurant.id}</a>)
	</h1>



	<c:if test="${not empty message}">
		<div id="message" class="${message.type}">${message.message}</div>
	</c:if>

	<table>
		<thead>
			<tr>
				<th>${labelCurrentOrder}</th>
				<th><spring:url var="submitOrderUrl"
						value="/diningTables/${diningTable.id}" /> <form:form
						name="submitOrderForm" action="${submitOrderUrl}" method="put">
						<input type="hidden" name="event" value="submitOrder" />
						<table>
							<tr>
								<td><input type="submit" value="${labelSubmitOrderButton}" /></td>
							</tr>
						</table>
					</form:form></th>
			</tr>
		</thead>
		<tbody>
			<c:forEach items="${diningTable.currentBill.currentOrder.orderItems}"
				var="orderItem">
				<tr>
					<td>${orderItem.menuItem.id} (${orderItem.quantity}x)</td>
				</tr>
			</c:forEach>
		</tbody>
	</table>


	<table>
		<thead>
			<tr>
				<th>${labelCurrentBill}</th>
				<th><spring:url var="submitBillUrl"
						value="/diningTables/${diningTable.id}" /> <form:form
						name="submitBillForm" action="${submitBillUrl}" method="put">
						<input type="hidden" name="event" value="submitBill" />
						<table>
							<tr>
								<td><input type="submit" value="${labelSubmitBillButton}" /></td>
							</tr>
						</table>
					</form:form></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>${labelPriceCurrentOrder}:
					${diningTable.currentBill.currentOrder.price}</td>
			</tr>
			<tr>
				<td>${labelTotalPricePrevOrders}:
					${diningTable.currentBill.priceSubmittedOrSuccessiveStateOrders}</td>
			</tr>
		</tbody>
	</table>

	<div id="tabs">
		<ul>
			<c:forEach items="${restaurant.menu.foodCategories}"
				var="foodCategory">
				<li><a href="#tabs-${foodCategory.id}">${foodCategory.tag}</a></li>
			</c:forEach>
		</ul>
		<c:forEach items="${restaurant.menu.foodCategories}"
			var="foodCategory">
			<div id="tabs-${foodCategory.id}">
				<c:forEach items="${foodCategory.menuItems}" var="menuItem">
					<spring:url var="imageUrl"
						value="/resources/images/${menuItem.imageFileName}" />
					<div id="menuitem">
						<div>${menuItem.id}</div>
						<div>
							<img id="menuitemimg" src="${imageUrl}" />
						</div>
						${labelPrice} ${menuItem.price} ${labelCurrency}
						<spring:url var="addOrderItemUrl"
							value="/diningTables/${diningTable.id}/menuItems" />
						<form:form name="addOrderItemForm" action="${addOrderItemUrl}"
							method="post">
							<input type="hidden" name="menuItemName" value="${menuItem.id}" />
							<table>
								<tr>
									<td><input type="submit" value="${labelAddButton}" /></td>
								</tr>
							</table>
						</form:form>
						<spring:url var="deleteOrderItemUrl"
							value="/diningTables/${diningTable.id}/menuItems/${menuItem.id}" />
						<form:form name="deleteOrderItemForm"
							action="${deleteOrderItemUrl}" method="delete">
							<table>
								<tr>
									<td><input type="submit" value="${labelRemoveButton}" /></td>
								</tr>
							</table>
						</form:form>
					</div>
				</c:forEach>

			</div>
		</c:forEach>
	</div>
</div>

src/main/webapp/WEB-INF/views/hartigehap/kitchen.jspx
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<div id="body" xmlns:jsp="http://java.sun.com/JSP/Page"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:joda="http://www.joda.org/joda/time/tags" version="2.0"
	xmlns:spring="http://www.springframework.org/tags"
	xmlns:form="http://www.springframework.org/tags/form" 
	xmlns:sec="http://www.springframework.org/security/tags">
	<jsp:directive.page contentType="text/html;charset=UTF-8" />
	<jsp:output omit-xml-declaration="yes" />

	<spring:message code="label_kitchen_subsystem" var="labelKitchenSubsystem" />
	<spring:message code="label_restaurant" var="labelRestaurant" />
	<spring:message code="label_all_submitted_orders" var="labelAllSubmittedOrders" />
	<spring:message code="label_submitted_order" var="labelSubmittedOrder" />
	<spring:message code="label_plan_order_button" var="labelPlanOrderButton" />
	<spring:message code="label_all_planned_orders" var="labelAllPlannedOrders" />
	<spring:message code="label_planned_order" var="labelPlannedOrder" />
	<spring:message code="label_prepared_order_button" var="labelPreparedOrderButton" />

	<spring:url var="showRestaurant" value="/restaurants/${restaurant.id}" />
	
	<h1>${labelKitchenSubsystem} (${labelRestaurant} <a href="${showRestaurant}">${restaurant.id}</a>)</h1>
	
	<c:if test="${not empty message}">
		<div id="message" class="${message.type}">${message.message}</div>
	</c:if>

	<table>
		<thead>
			<tr>
				<th>${labelAllSubmittedOrders}</th><th></th>
			</tr>
		</thead>
		<tbody>
			<c:forEach items="${allSubmittedOrders}" var="submittedOrder">
				<tr>
					<spring:url var="showOrder" value="/kitchen/orders/${submittedOrder.id}" />
					<td>
						<a href="${showOrder}">${labelSubmittedOrder} ${submittedOrder.bill.diningTable.tableNr}</a></td>
					<td>
						<sec:authorize access="hasRole('ROLE_EMPLOYEE')">
							<spring:url var="planOrderUrl"
								value="/kitchen/orders/${submittedOrder.id}" />
							<form:form name="planOrderForm" action="${planOrderUrl}" method="put">
								<input type="hidden" name="event" value="planOrder" />
								<table>
									<tr>
										<td><input type="submit" value="${labelPlanOrderButton}" /></td>
									</tr>
								</table>
							</form:form>
						</sec:authorize>
					</td>
				</tr>
			</c:forEach>
		</tbody>
	</table>


	<table>
		<thead>
			<tr>
				<th>${labelAllPlannedOrders}</th><th></th>
			</tr>
		</thead>
		<tbody>
			<c:forEach items="${allPlannedOrders}" var="plannedOrder">
				<tr>
					<spring:url var="showOrder" value="/kitchen/orders/${plannedOrder.id}" />
					<td>
						<a href="${showOrder}">${labelPlannedOrder} ${plannedOrder.bill.diningTable.tableNr}</a></td>
					<td>
						<sec:authorize access="hasRole('ROLE_EMPLOYEE')">
							<spring:url var="preparedOrderUrl"
								value="/kitchen/orders/${plannedOrder.id}" />
							<form:form name="preparedOrderForm" action="${preparedOrderUrl}" method="put">
								<input type="hidden" name="event" value="orderHasBeenPrepared" />
								<table>
									<tr>
										<td><input type="submit" value="${labelPreparedOrderButton}" /></td>
									</tr>
								</table>
							</form:form>
						</sec:authorize>
					</td>
				</tr>
			</c:forEach>
		</tbody>
	</table>

</div>

src/main/webapp/WEB-INF/views/hartigehap/listrestaurants.jspx
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<div id="body" xmlns:jsp="http://java.sun.com/JSP/Page"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:joda="http://www.joda.org/joda/time/tags"
	xmlns:spring="http://www.springframework.org/tags" version="2.0"
	xmlns:sec="http://www.springframework.org/security/tags">
	<jsp:directive.page contentType="text/html;charset=UTF-8" />
	<jsp:output omit-xml-declaration="yes" />


	<spring:message code="label_restaurant_overview" var="labelRestaurantOverview" />
	<spring:message code="label_restaurants" var="labelRestaurants" />
	<spring:message code="label_admin_area" var="labelAdminArea" />
	<spring:message code="label_create_harigehap" var="labelCreateHarigeHap" />
	<spring:message code="label_create_plakkerigepannekoek" var="labelCreatePlakkerigePannekoek" />
	<spring:message code="label_create_huilendehamburger" var="labelCreateHuilendeHamburger" />
	<spring:message code="label_create_button" var="labelCreateButton" />

	<h1>${labelRestaurantOverview}</h1>

	<c:if test="${not empty message}">
		<div id="message" class="${message.type}">${message.message}</div>
	</c:if>

	<table>
		<thead>
			<tr>
				<th>${labelRestaurants}</th>
			</tr>
		</thead>
		<tbody>
			<c:forEach items="${restaurants}" var="restaurant">
				<spring:url var="showRestaurant" value="/restaurants/${restaurant.id}" />					
				<tr>
					<td><a href="${showRestaurant}">${restaurant.id}</a></td>							
				</tr>
			</c:forEach>
		</tbody>
	</table>
</div>